---
- name: "update apt packages."
  become: true
  apt:
    update_cache: true

- name: "upgrade packages."
  become: true
  apt:
    upgrade: "yes"
    
- name: install kubernetes
  become: yes
  shell: |
    # Installing minikube according to standard documentation (https://minikube.sigs.k8s.io/docs/start/)
    curl -LO https://storage.googleapis.com/minikube/releases/latest/minikube-linux-amd64
    sudo install minikube-linux-amd64 /usr/local/bin/minikube
    # Installing and verifying kubectl according to standard documentation (https://kubernetes.io/docs/tasks/tools/install-kubectl-linux/)
    curl -LO "https://dl.k8s.io/release/$(curl -L -s https://dl.k8s.io/release/stable.txt)/bin/linux/amd64/kubectl"
    curl -LO "https://dl.k8s.io/$(curl -L -s https://dl.k8s.io/release/stable.txt)/bin/linux/amd64/kubectl.sha256"
    echo "$(<kubectl.sha256) kubectl" | sha256sum --check
    sudo install -o root -g root -m 0755 kubectl /usr/local/bin/kubectl
    kubectl version --client
    
- name: download docker image
  become: yes
  shell: |
    # This is your Docker ID/path
    dockerpath="bencdr0/nginxapp"
    # Step 2
    # Run the Docker Hub container with kubernetes
    kubectl run nginxapp --image=$dockerpath --port=80 --labels app=nginxapp
    # Step 3:
    # List kubernetes pods
    kubectl get pods
    # Step 4:
    # Forward the container port to a host
    kubectl port-forward nginxapp 8000:80
