---
- name: Find out playbooks path
  shell: pwd
  register: playbook_path_output
- debug: var=playbook_path_output.stdout


- name: "create backend directory"
  become: yes
  file:
    path: ~/backend
    state: directory
    mode: '0755'

- name: "copy file to backend infrastructure"
  become: true
  copy:
    src: /root/project/artifact.tar.gz
    dest: /home/ubuntu/backend
    remote_src: false
    mode: '0777'

- name: "extract zipped artifact"
  become: yes
  shell:  |
    cd /home/ubuntu/backend
    tar -xf artifact.tar.gz

- name: "run application"
  shell:  |
    cd /home/ubuntu/backend
    npm install
    pm2 stop default
    pm2 start npm -- start
    pm2 status
    cd dist
    pm2 start main.js --update-env
    register: playbook_path_output2
- debug: var=playbook_path_output2.stdout